[package]
name = "csvdsl"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = "4.5.49"
clap_derive = "4.5.49"
serde = { version = "1.0.228", features=["derive"]}
serde_json = "1.0.145"
serde_yaml = "0.9.34"
