- name: title
  aliases: 
    - Work Title
    - Title
    - song_name
    - Work Primary Title
    - Track Name
  optional: false
  type: String

- name: earnings
  aliases: 
    - USD Amount
    - $ Amount
    - Amount
    - Dollars
    - amount_received
    - Earnings (USD)
    - Distributed Amount
    - Your Payment Amount
  optional: false
  type: Float

- name: date
  aliases:
    - Distribution Date
    - start_date
    - Transaction Date
  type: Date
  optional: true

- name: artist
  aliases: 
    - Performing Artist
    - Artist
    - Recording Display Artist Name
    - Artist Name
  optional: true
  type: String

- name: licensor
  aliases:
    - Licensor
  optional: true
  type: String

- name: isrc
  aliases:
    - ISRC
    - isrc
  type: String

- name: iswc
  aliases: 
    - iswc
    - ISWC
  optional: true
  type: String

- name: upc
  aliases: 
    - UPC
    - Album UPC
    - Release UPC
  optional: true
  type: Uint

- name: territory
  aliases:
   - Territory
  optional: true
  type: Country

# type Country is essentially a string but serializes country codes to name
