- name: title
  aliases: [ "Work Title", "Title" ]
  optional: false
  type: String

- name: earnings
  aliases: [ "USD Amount", "$ Amount", "Amount", "Dollars" ]
  optional: false
  type: Float

- name: artist
  aliases: [ "Performing Artist", "Artist" ]
  type: String

- name: isrc
  aliases: [ "ISRC" ]
  type: String

- name: upc
  aliases: [ "UPC", "Album UPC" ]
  optional: true
  type: Uint

- name: territory
  aliases: [ "Territory" ]
  optional: true
  type: String
